language: c

cache:
  directories:
    - nim

env:
  global:
    - REPONAME="$(basename ${TRAVIS_BUILD_DIR})" # /travis/build/kaushalmodi/version -> version
    #
    - NIMREPO="https://github.com/nim-lang/Nim"
    - NIMVER="$(git ls-remote ${NIMREPO} devel | cut -f 1)"
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"
    #
    - NIMFILE="${TRAVIS_BUILD_DIR}/src/${REPONAME}.nim"
    - BINFILE="${TRAVIS_BUILD_DIR}/src/${REPONAME}"
    #
    - DIST_DIR="${TRAVIS_BUILD_DIR}/dist"
    - ASSETFILE="${REPONAME}-${TRAVIS_TAG}.Linux_64bit_musl.tar.xz"

addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools

install:
  - echo "NIMDIR = ${NIMDIR}"
  - |
    if [[ ! -f "${NIMDIR}/bin/nim" ]]
    then
      rm -rf nim
      mkdir -p nim
      git clone --single-branch --branch devel --depth=1 "${NIMREPO}" "${NIMDIR}"
      cd "${NIMDIR}" || exit
      [ -d csources ] || git clone --depth 1 https://github.com/nim-lang/csources.git
      cd csources
      sh build.sh
      cd ..
      # After building nim, wipe csources to save on cache space.
      rm -rf csources
    fi
  - |
    if [[ ! -f "${NIMDIR}/bin/nimble" ]]
    then
      cd "${NIMDIR}" || exit
      ./koch nimble
    fi
  - export PATH="${NIMDIR}/bin:${PATH}"

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - nim -v
  - nim pullConfig
  - nim musl "${NIMFILE}"
  - file "${BINFILE}"
  - eval "${BINFILE} nim"
  - nim test
  - nim docs

before_deploy:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p "${DIST_DIR}"
  - cp "${BINFILE}" "${DIST_DIR}"/.
  # -C <DIR> tells tar to change the current directory to <DIR>, and
  # then the "." means "add the entire current directory" (including
  # hidden files and sub-directories).
  - tar caf "${ASSETFILE}" -C "${DIST_DIR}" .

deploy:
  - provider: pages
    # local-dir *has* to be a relative path from the repo root.
    local-dir: "public"
    skip-cleanup: true
    github-token: "${GITHUB_OAUTH_TOKEN}"
    keep-history: false
    on:
      branch: master
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: "${ASSETFILE}"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
